name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip:
      - protobuf==3.19.0
      - wandb==0.10.21